import { listingPhoto } from "./productImages";
import type { ProductProvenance } from "./productProvenanceTypes";
import { STORY_DATA } from "./productStories";

export type Condition = "pristine" | "excellent" | "very-good" | "good";
export type Category =
  | "bags"
  | "shoes"
  | "clothing"
  | "accessories"
  | "belts"
  | "jewelry";

export interface Product {
  id: string;
  name: string;
  brand: string;
  brandDisplay: string;
  category: Category;
  price: number;
  originalPrice: number;
  condition: Condition;
  color: string;
  material?: string;
  size?: string;
  year?: number;
  image: string;
  description: string;
  authenticated: boolean;
  featured?: boolean;
  /** Human provenance — merged from [lib/productStories.ts](lib/productStories.ts) */
  provenance?: ProductProvenance;
  storyBody?: string;
}

export interface Brand {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  founded: number;
  country: string;
}

export const BRANDS: Brand[] = [
  {
    slug: "hermes",
    name: "Hermès",
    tagline: "The pinnacle of French luxury",
    description:
      "Founded in Paris in 1837, Hermès is synonymous with the ultimate in craftsmanship. Each piece is made by a single artisan and may take up to 48 hours to complete.",
    founded: 1837,
    country: "France",
  },
  {
    slug: "louis-vuitton",
    name: "Louis Vuitton",
    tagline: "Icons of French craftsmanship",
    description:
      "The world's most valuable luxury brand, Louis Vuitton has been synonymous with travel, elegance, and craftsmanship since 1854.",
    founded: 1854,
    country: "France",
  },
  {
    slug: "chanel",
    name: "Chanel",
    tagline: "Timeless Parisian elegance",
    description:
      "Gabrielle 'Coco' Chanel revolutionised women's fashion in 1910. Today, the house remains the epitome of Parisian chic.",
    founded: 1910,
    country: "France",
  },
  {
    slug: "gucci",
    name: "Gucci",
    tagline: "Italian luxury redefined",
    description:
      "From a Florentine leather goods shop founded in 1921, Gucci has grown into one of the world's most recognisable luxury houses.",
    founded: 1921,
    country: "Italy",
  },
  {
    slug: "prada",
    name: "Prada",
    tagline: "Milanese intellectual fashion",
    description:
      "Since 1913, Prada has stood at the intersection of fashion and intellect — classic craftsmanship with a subversive edge.",
    founded: 1913,
    country: "Italy",
  },
  {
    slug: "dior",
    name: "Christian Dior",
    tagline: "Haute couture at its finest",
    description:
      "Christian Dior's 1947 New Look transformed fashion. Today the house blends heritage with contemporary vision under its creative directors.",
    founded: 1946,
    country: "France",
  },
  {
    slug: "balenciaga",
    name: "Balenciaga",
    tagline: "Avant-garde luxury fashion",
    description:
      "Founded by Cristóbal Balenciaga in 1917, the house is now fashion's most provocative voice, redefining what luxury means.",
    founded: 1919,
    country: "Spain",
  },
  {
    slug: "saint-laurent",
    name: "Saint Laurent",
    tagline: "Parisian rock and roll luxury",
    description:
      "Yves Saint Laurent's 1961 founding house brought a new kind of power to women's fashion — sensual, sharp, and unapologetically Parisian.",
    founded: 1961,
    country: "France",
  },
];

const productsBase: Product[] = [
  {
    id: "1",
    name: "Birkin 30 Togo Leather",
    brand: "hermes",
    brandDisplay: "Hermès",
    category: "bags",
    price: 60000,
    originalPrice: 220000,
    condition: "excellent",
    color: "Noir",
    material: "Togo leather",
    size: "30cm",
    year: 2021,
    image: listingPhoto("bags", "1"),
    description:
      "A stunning Hermès Birkin 30 in Noir Togo leather with palladium hardware. Sourced and authenticated by VAULTED. Full set including original orange box, dust bag, lock, keys, and documentation. Minimal wear — stored and handled with care.",
    authenticated: true,
    featured: true,
  },
  {
    id: "2",
    name: "Neverfull MM Monogram",
    brand: "louis-vuitton",
    brandDisplay: "Louis Vuitton",
    category: "bags",
    price: 7000,
    originalPrice: 14000,
    condition: "very-good",
    color: "Brown Monogram",
    material: "Coated canvas",
    size: "MM",
    year: 2019,
    image: listingPhoto("bags", "2"),
    description:
      "Classic Louis Vuitton Neverfull MM in the iconic monogram canvas with rose ballerine interior. Light signs of use on corners, overall in great shape. Comes with original dust bag.",
    authenticated: true,
    featured: true,
  },
  {
    id: "3",
    name: "Classic Flap Medium Caviar",
    brand: "chanel",
    brandDisplay: "Chanel",
    category: "bags",
    price: 34000,
    originalPrice: 70000,
    condition: "pristine",
    color: "Navy",
    material: "Caviar leather",
    size: "Medium",
    year: 2022,
    image: listingPhoto("bags", "3"),
    description:
      "Barely used Chanel Classic Flap in deep navy caviar leather with gold hardware. Authentication documentation included. Comes with original box, dust bag, and ribbon.",
    authenticated: true,
    featured: true,
  },
  {
    id: "4",
    name: "GG Marmont Shoulder Bag",
    brand: "gucci",
    brandDisplay: "Gucci",
    category: "bags",
    price: 6500,
    originalPrice: 18000,
    condition: "excellent",
    color: "Black",
    material: "Matelassé chevron leather",
    year: 2020,
    image: listingPhoto("bags", "4"),
    description:
      "Gucci GG Marmont small shoulder bag in black matelassé chevron leather with antique gold hardware. Signature GG logo plate on back. Comes with original dust bag.",
    authenticated: true,
  },
  {
    id: "5",
    name: "Galleria Saffiano Leather Tote",
    brand: "prada",
    brandDisplay: "Prada",
    category: "bags",
    price: 12000,
    originalPrice: 30000,
    condition: "excellent",
    color: "Caramel",
    material: "Saffiano leather",
    year: 2020,
    image: listingPhoto("bags", "5"),
    description:
      "Prada Galleria bag in warm caramel Saffiano leather with silver hardware. Light use, interior is immaculate. Comes with dust bag.",
    authenticated: true,
    featured: true,
  },
  {
    id: "6",
    name: "Saddle Bag Grained Calfskin",
    brand: "dior",
    brandDisplay: "Christian Dior",
    category: "bags",
    price: 15000,
    originalPrice: 38000,
    condition: "very-good",
    color: "Tan",
    material: "Grained calfskin",
    year: 2021,
    image: listingPhoto("bags", "6"),
    description:
      "Iconic Christian Dior Saddle bag in tan grained calfskin with silver CD clasp. Light wear on the base corners. Comes with original packaging and dust bag.",
    authenticated: true,
  },
  {
    id: "7",
    name: "Track Sneakers",
    brand: "balenciaga",
    brandDisplay: "Balenciaga",
    category: "shoes",
    price: 2800,
    originalPrice: 6500,
    condition: "very-good",
    color: "White / Grey",
    size: "EU 41",
    year: 2022,
    image: listingPhoto("shoes", "7"),
    description:
      "Balenciaga Track sneakers in white with grey and black panel details. Worn lightly; comes with original box and extra laces.",
    authenticated: true,
  },
  {
    id: "8",
    name: "Tribute Platform Sandals",
    brand: "saint-laurent",
    brandDisplay: "Saint Laurent",
    category: "shoes",
    price: 3200,
    originalPrice: 8000,
    condition: "excellent",
    color: "Nude",
    size: "EU 37",
    year: 2021,
    image: listingPhoto("shoes", "8"),
    description:
      "Saint Laurent Tribute platform sandals in nude satin with suede details. Worn twice; original box and dust bag included.",
    authenticated: true,
  },
  {
    id: "9",
    name: "Reversible Monogram Belt 90cm",
    brand: "louis-vuitton",
    brandDisplay: "Louis Vuitton",
    category: "belts",
    price: 1900,
    originalPrice: 4200,
    condition: "excellent",
    color: "Brown / Black",
    size: "90cm",
    year: 2020,
    image: listingPhoto("belts", "9"),
    description:
      "Louis Vuitton reversible belt in monogram canvas and black leather with gold LV buckle. Barely worn with original box.",
    authenticated: true,
  },
  {
    id: "10",
    name: "GG Marmont Leather Belt 85cm",
    brand: "gucci",
    brandDisplay: "Gucci",
    category: "belts",
    price: 1500,
    originalPrice: 3400,
    condition: "very-good",
    color: "Black",
    size: "85cm",
    year: 2021,
    image: listingPhoto("belts", "10"),
    description:
      "Gucci GG Marmont belt in black leather with antique gold double G buckle. Light use; original box included.",
    authenticated: true,
  },
  {
    id: "11",
    name: "Kelly 25 Epsom Leather",
    brand: "hermes",
    brandDisplay: "Hermès",
    category: "bags",
    price: 80000,
    originalPrice: 260000,
    condition: "pristine",
    color: "Gold",
    material: "Epsom leather",
    size: "25cm",
    year: 2023,
    image: listingPhoto("bags", "11"),
    description:
      "Hermès Kelly 25 Sellier in Gold Epsom with palladium hardware. Pristine condition with lock, keys, clochette, mirror, rain cover, and full documentation.",
    authenticated: true,
    featured: true,
  },
  {
    id: "12",
    name: "Re-Edition 2000 Nylon Mini Bag",
    brand: "prada",
    brandDisplay: "Prada",
    category: "bags",
    price: 4200,
    originalPrice: 12000,
    condition: "excellent",
    color: "Blush Pink",
    material: "Re-Nylon",
    year: 2022,
    image: listingPhoto("bags", "12"),
    description:
      "Prada Re-Edition 2000 in blush pink Re-Nylon. Minimal use with dust bag and original packaging.",
    authenticated: true,
  },
  {
    id: "13",
    name: "Oran Sandals",
    brand: "hermes",
    brandDisplay: "Hermès",
    category: "shoes",
    price: 4200,
    originalPrice: 7000,
    condition: "excellent",
    color: "Gold",
    material: "Leather",
    size: "EU 38",
    year: 2022,
    image: listingPhoto("shoes", "13"),
    description:
      "Hermès Oran sandals in gold Epsom leather. Light sole wear; otherwise excellent. Dust bags included.",
    authenticated: true,
  },
  {
    id: "14",
    name: "Clic H Bracelet PM",
    brand: "hermes",
    brandDisplay: "Hermès",
    category: "jewelry",
    price: 5000,
    originalPrice: 8500,
    condition: "excellent",
    color: "White / Palladium",
    material: "Enamel",
    size: "PM",
    year: 2021,
    image: listingPhoto("jewelry", "14"),
    description:
      "Hermès Clic H bracelet in white enamel with palladium hardware. Minimal hairline marks; presentation box included.",
    authenticated: true,
    featured: true,
  },
  {
    id: "15",
    name: "Speedy 30 Monogram",
    brand: "louis-vuitton",
    brandDisplay: "Louis Vuitton",
    category: "bags",
    price: 8500,
    originalPrice: 13000,
    condition: "very-good",
    color: "Monogram",
    material: "Coated canvas",
    size: "30",
    year: 2018,
    image: listingPhoto("bags", "15"),
    description:
      "Louis Vuitton Speedy 30 in classic monogram. Handles honeyed; corners show light use. Lock and key included.",
    authenticated: true,
  },
  {
    id: "16",
    name: "Keepall Bandoulière 45",
    brand: "louis-vuitton",
    brandDisplay: "Louis Vuitton",
    category: "bags",
    price: 11000,
    originalPrice: 17000,
    condition: "excellent",
    color: "Monogram Eclipse",
    material: "Coated canvas",
    size: "45",
    year: 2020,
    image: listingPhoto("bags", "16"),
    description:
      "Louis Vuitton Keepall 45 in Monogram Eclipse with strap. Travel-ready; light use only.",
    authenticated: true,
    featured: true,
  },
  {
    id: "17",
    name: "Espadrilles CC",
    brand: "chanel",
    brandDisplay: "Chanel",
    category: "shoes",
    price: 3800,
    originalPrice: 6500,
    condition: "very-good",
    color: "Black",
    material: "Canvas / leather",
    size: "EU 39",
    year: 2021,
    image: listingPhoto("shoes", "17"),
    description:
      "Chanel classic espadrilles in black canvas with cap toe. Soles show light wear.",
    authenticated: true,
  },
  {
    id: "18",
    name: "Wallet on Chain Caviar",
    brand: "chanel",
    brandDisplay: "Chanel",
    category: "accessories",
    price: 14000,
    originalPrice: 26000,
    condition: "excellent",
    color: "Black",
    material: "Caviar leather",
    year: 2022,
    image: listingPhoto("accessories", "18"),
    description:
      "Chanel WOC in black caviar with gold hardware. Interior organised; authenticity card included.",
    authenticated: true,
  },
  {
    id: "19",
    name: "Ace Leather Sneakers",
    brand: "gucci",
    brandDisplay: "Gucci",
    category: "shoes",
    price: 3400,
    originalPrice: 6000,
    condition: "good",
    color: "White",
    material: "Leather",
    size: "EU 42",
    year: 2019,
    image: listingPhoto("shoes", "19"),
    description:
      "Gucci Ace sneakers in white leather with web stripe. Soles and heel counters show wear.",
    authenticated: true,
  },
  {
    id: "20",
    name: "Cahier Shoulder Bag",
    brand: "prada",
    brandDisplay: "Prada",
    category: "bags",
    price: 13000,
    originalPrice: 28000,
    condition: "excellent",
    color: "Black",
    material: "Saffiano",
    year: 2020,
    image: listingPhoto("bags", "20"),
    description:
      "Prada Cahier in black Saffiano with brass hardware. Structured silhouette; dust bag included.",
    authenticated: true,
  },
  {
    id: "21",
    name: "America's Cup Sneakers",
    brand: "prada",
    brandDisplay: "Prada",
    category: "shoes",
    price: 3000,
    originalPrice: 6000,
    condition: "very-good",
    color: "Silver / Black",
    material: "Mesh / leather",
    size: "EU 43",
    year: 2021,
    image: listingPhoto("shoes", "21"),
    description:
      "Prada America's Cup in silver mesh with bike sole. Clean overall with light sole wear.",
    authenticated: true,
  },
  {
    id: "22",
    name: "B23 High-Top Sneakers",
    brand: "dior",
    brandDisplay: "Christian Dior",
    category: "shoes",
    price: 4600,
    originalPrice: 8500,
    condition: "excellent",
    color: "Oblique",
    material: "Canvas / leather",
    size: "EU 41",
    year: 2022,
    image: listingPhoto("shoes", "22"),
    description:
      "Dior B23 high-tops in Dior Oblique canvas. Worn sparingly; box and dust bags included.",
    authenticated: true,
  },
  {
    id: "23",
    name: "Tribales Earrings",
    brand: "dior",
    brandDisplay: "Christian Dior",
    category: "jewelry",
    price: 2600,
    originalPrice: 4200,
    condition: "excellent",
    color: "White resin / gold",
    material: "Metal / resin",
    year: 2021,
    image: listingPhoto("jewelry", "23"),
    description:
      "Dior Tribales earrings in white resin pearls. Minimal wear; jewellery pouch included.",
    authenticated: true,
  },
  {
    id: "24",
    name: "Classic City Medium",
    brand: "balenciaga",
    brandDisplay: "Balenciaga",
    category: "bags",
    price: 6500,
    originalPrice: 18000,
    condition: "very-good",
    color: "Black",
    material: "Agneau leather",
    year: 2019,
    image: listingPhoto("bags", "24"),
    description:
      "Balenciaga City in black distressed leather with giant hardware. Corners softened; mirror included.",
    authenticated: true,
  },
  {
    id: "25",
    name: "Political Logo Hoodie",
    brand: "balenciaga",
    brandDisplay: "Balenciaga",
    category: "clothing",
    price: 4200,
    originalPrice: 10000,
    condition: "excellent",
    color: "Black",
    material: "Cotton",
    size: "M",
    year: 2021,
    image: listingPhoto("clothing", "25"),
    description:
      "Balenciaga oversized hoodie in black fleece. Light wash wear; tags available.",
    authenticated: true,
  },
  {
    id: "26",
    name: "Loulou Small Matelassé",
    brand: "saint-laurent",
    brandDisplay: "Saint Laurent",
    category: "bags",
    price: 11000,
    originalPrice: 22000,
    condition: "excellent",
    color: "Black",
    material: "Matelassé leather",
    year: 2022,
    image: listingPhoto("bags", "26"),
    description:
      "Saint Laurent Loulou small in black matelassé with chain strap. Dust bag and cards included.",
    authenticated: true,
    featured: true,
  },
  {
    id: "27",
    name: "L01 Leather Biker Jacket",
    brand: "saint-laurent",
    brandDisplay: "Saint Laurent",
    category: "clothing",
    price: 26000,
    originalPrice: 44000,
    condition: "excellent",
    color: "Black",
    material: "Lambskin",
    size: "FR 48",
    year: 2020,
    image: listingPhoto("clothing", "27"),
    description:
      "Saint Laurent classic motorcycle jacket in black lambskin. Supple leather; light creasing at elbows.",
    authenticated: true,
  },
  {
    id: "28",
    name: "Constance Slim Wallet",
    brand: "hermes",
    brandDisplay: "Hermès",
    category: "accessories",
    price: 8500,
    originalPrice: 14000,
    condition: "excellent",
    color: "Étoupe",
    material: "Epsom",
    year: 2022,
    image: listingPhoto("accessories", "28"),
    description:
      "Hermès Constance Slim wallet in Étoupe Epsom with H clasp. Minimal use.",
    authenticated: true,
  },
  {
    id: "29",
    name: "Monogram Silk Bandeau",
    brand: "louis-vuitton",
    brandDisplay: "Louis Vuitton",
    category: "accessories",
    price: 1100,
    originalPrice: 2600,
    condition: "pristine",
    color: "Monogram",
    material: "Silk",
    year: 2023,
    image: listingPhoto("accessories", "29"),
    description:
      "Louis Vuitton silk bandeau in monogram print. Unused with ribbon and box.",
    authenticated: true,
  },
  {
    id: "30",
    name: "Chanel 19 Flap Small",
    brand: "chanel",
    brandDisplay: "Chanel",
    category: "bags",
    price: 32000,
    originalPrice: 50000,
    condition: "excellent",
    color: "Beige",
    material: "Goatskin",
    size: "Small",
    year: 2022,
    image: listingPhoto("bags", "30"),
    description:
      "Chanel 19 small in beige goatskin with mixed metals. Light use; full set.",
    authenticated: true,
    featured: true,
  },
  {
    id: "31",
    name: "Dionysus GG Supreme Mini",
    brand: "gucci",
    brandDisplay: "Gucci",
    category: "bags",
    price: 7500,
    originalPrice: 17000,
    condition: "very-good",
    color: "Taupe",
    material: "GG Supreme",
    year: 2020,
    image: listingPhoto("bags", "31"),
    description:
      "Gucci Dionysus mini in GG Supreme with taupe suede. Tiger closure bright; chain included.",
    authenticated: true,
  },
  {
    id: "32",
    name: "Symbole Sunglasses",
    brand: "prada",
    brandDisplay: "Prada",
    category: "accessories",
    price: 1700,
    originalPrice: 3200,
    condition: "excellent",
    color: "Black",
    material: "Acetate",
    year: 2022,
    image: listingPhoto("accessories", "32"),
    description:
      "Prada Symbole rectangular sunglasses with case and cloth.",
    authenticated: true,
  },
  {
    id: "33",
    name: "Small Book Tote",
    brand: "dior",
    brandDisplay: "Christian Dior",
    category: "bags",
    price: 13000,
    originalPrice: 18000,
    condition: "excellent",
    color: "Toile de Jouy",
    material: "Embroidered canvas",
    year: 2021,
    image: listingPhoto("bags", "33"),
    description:
      "Dior Book Tote small in toile embroidery. Handles clean; dust bag included.",
    authenticated: true,
  },
  {
    id: "34",
    name: "H Belt 32mm Reversible",
    brand: "hermes",
    brandDisplay: "Hermès",
    category: "belts",
    price: 4200,
    originalPrice: 7000,
    condition: "excellent",
    color: "Noir / Gold",
    material: "Epsom",
    size: "85cm",
    year: 2021,
    image: listingPhoto("belts", "34"),
    description:
      "Hermès 32mm H belt reversible Noir and Gold with brushed gold buckle.",
    authenticated: true,
  },
  {
    id: "35",
    name: "LV Trainer Sneaker",
    brand: "louis-vuitton",
    brandDisplay: "Louis Vuitton",
    category: "shoes",
    price: 6500,
    originalPrice: 10000,
    condition: "very-good",
    color: "White / Monogram",
    material: "Leather",
    size: "EU 9",
    year: 2022,
    image: listingPhoto("shoes", "35"),
    description:
      "Louis Vuitton Trainer sneaker in white calf with monogram panels. Soles show wear.",
    authenticated: true,
  },
  {
    id: "36",
    name: "Slingback Pumps Grosgrain",
    brand: "chanel",
    brandDisplay: "Chanel",
    category: "shoes",
    price: 4600,
    originalPrice: 7500,
    condition: "excellent",
    color: "Beige / Black",
    material: "Grosgrain",
    size: "EU 38.5",
    year: 2021,
    image: listingPhoto("shoes", "36"),
    description:
      "Chanel slingbacks in beige grosgrain with black cap toe. Worn twice.",
    authenticated: true,
  },
  {
    id: "37",
    name: "Ophidia GG Card Case",
    brand: "gucci",
    brandDisplay: "Gucci",
    category: "accessories",
    price: 1500,
    originalPrice: 2800,
    condition: "excellent",
    color: "GG Supreme",
    material: "Canvas / leather",
    year: 2022,
    image: listingPhoto("accessories", "37"),
    description:
      "Gucci Ophidia card case in GG Supreme with green/red web. Box included.",
    authenticated: true,
  },
  {
    id: "38",
    name: "Cloudbust Thunder",
    brand: "prada",
    brandDisplay: "Prada",
    category: "shoes",
    price: 3800,
    originalPrice: 7500,
    condition: "good",
    color: "White / Silver",
    material: "Rubber / knit",
    size: "EU 40",
    year: 2021,
    image: listingPhoto("shoes", "38"),
    description:
      "Prada Cloudbust Thunder in white with sculpted sole. Notable sole wear.",
    authenticated: true,
  },
  {
    id: "39",
    name: "Hourglass Top Handle XS",
    brand: "balenciaga",
    brandDisplay: "Balenciaga",
    category: "bags",
    price: 10000,
    originalPrice: 17000,
    condition: "excellent",
    color: "Black",
    material: "Calfskin",
    year: 2022,
    image: listingPhoto("bags", "39"),
    description:
      "Balenciaga Hourglass XS in black box calf with B hardware. Sharp corners; strap included.",
    authenticated: true,
    featured: true,
  },
  {
    id: "40",
    name: "Monogram Card Holder",
    brand: "saint-laurent",
    brandDisplay: "Saint Laurent",
    category: "accessories",
    price: 1100,
    originalPrice: 2200,
    condition: "pristine",
    color: "Black",
    material: "Grained leather",
    year: 2023,
    image: listingPhoto("accessories", "40"),
    description:
      "Saint Laurent monogram card holder in black grain de poudre. Unused with box.",
    authenticated: true,
  },
  {
    id: "41",
    name: "Capucines BB",
    brand: "louis-vuitton",
    brandDisplay: "Louis Vuitton",
    category: "bags",
    price: 22000,
    originalPrice: 36000,
    condition: "excellent",
    color: "Galet",
    material: "Taurillon leather",
    year: 2022,
    image: listingPhoto("bags", "41"),
    description:
      "Louis Vuitton Capucines BB in Galet Taurillon. Light use; shoulder strap and dust bag.",
    authenticated: true,
    featured: true,
  },
  {
    id: "42",
    name: "Double G Wool Cardigan",
    brand: "gucci",
    brandDisplay: "Gucci",
    category: "clothing",
    price: 8500,
    originalPrice: 14000,
    condition: "excellent",
    color: "Navy",
    material: "Wool",
    size: "M",
    year: 2021,
    image: listingPhoto("clothing", "42"),
    description:
      "Gucci wool cardigan with gold double G buttons. Light pilling at cuffs.",
    authenticated: true,
  },
  {
    id: "43",
    name: "J'Adior Choker",
    brand: "dior",
    brandDisplay: "Christian Dior",
    category: "jewelry",
    price: 3800,
    originalPrice: 6000,
    condition: "excellent",
    color: "Antique gold",
    year: 2020,
    image: listingPhoto("jewelry", "43"),
    description:
      "Dior J'Adior choker with logo lettering. Presentation box included.",
    authenticated: true,
  },
  {
    id: "44",
    name: "Niki Medium Crinkled",
    brand: "saint-laurent",
    brandDisplay: "Saint Laurent",
    category: "bags",
    price: 14000,
    originalPrice: 22000,
    condition: "very-good",
    color: "Black",
    material: "Crinkled leather",
    year: 2021,
    image: listingPhoto("bags", "44"),
    description:
      "Saint Laurent Niki medium in black crinkled leather with chain. Corner rubs; authenticity card.",
    authenticated: true,
  },
  {
    id: "45",
    name: "Lindy 26 Clemence",
    brand: "hermes",
    brandDisplay: "Hermès",
    category: "bags",
    price: 55000,
    originalPrice: 100000,
    condition: "excellent",
    color: "Étoupe",
    material: "Clemence",
    size: "26",
    year: 2022,
    image: listingPhoto("bags", "45"),
    description:
      "Hermès Lindy 26 in Étoupe Clemence with palladium. Full set; light handle patina.",
    authenticated: true,
    featured: true,
  },
];

export const PRODUCTS: Product[] = productsBase.map((p) => ({
  ...p,
  ...(STORY_DATA[p.id] ?? {}),
}));

/** Personal listing title — shown as primary; falls back to catalog name */
export function listingDisplayTitle(product: Product): string {
  const h = product.provenance?.headline?.trim();
  return h || product.name;
}

/** One line for cards — headline, truncated story, or default */
export function productStoryTeaser(product: Product): string {
  if (product.provenance?.headline) return product.provenance.headline;
  if (product.storyBody) {
    const t = product.storyBody.trim();
    if (t.length <= 100) return t;
    return `${t.slice(0, 97)}…`;
  }
  if (product.provenance?.memory) return product.provenance.memory;
  return "A curated pre-loved piece with a story worth telling.";
}

export const CONDITION_LABELS: Record<Condition, string> = {
  pristine: "Pristine",
  excellent: "Excellent",
  "very-good": "Very Good",
  good: "Good",
};

export const CONDITION_COLORS: Record<Condition, string> = {
  pristine: "#b8965a",
  excellent: "#6b8f71",
  "very-good": "#7a8fb0",
  good: "#9c9491",
};

export const CATEGORIES: { value: Category; label: string }[] = [
  { value: "bags", label: "Bags" },
  { value: "shoes", label: "Shoes" },
  { value: "clothing", label: "Clothing" },
  { value: "accessories", label: "Accessories" },
  { value: "belts", label: "Belts" },
  { value: "jewelry", label: "Jewelry" },
];

export function getDiscount(price: number, originalPrice: number): number {
  return Math.round((1 - price / originalPrice) * 100);
}

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(price);
}
